# Site settings
title: Paulo Azoia
name: Paulo Azoia

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: StackOverflow
   url: https://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
techskills:
 - Ruby
 - Rspec
 - JavaScript
 - Jasmine
 - Sinatra
 - Bootstrap
 - Devise Controller
 - Capybara
 - Python
 - Pytest
 - Machine learning
 - HTML
 - CSS
 - Postgresql

personalskills:
 - Organisation
 - Attention to detail
 - Customer Service
 - Fluent English & Portuguese

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Software Developer Student
   start: 2019
   end: 2020
   employer: Makers Academy Bootcamp
   description: The bootcamp covered multiple languages throughout including Ruby, JavaScript and HTML which promoted the ability of being language agnostic and challenging me to apply these languages in practical projects. <br/><br/>
                Learning Test Driven Development and the long-term benefits of using it.<br/><br/>
                Regular research on new concepts, working on individual projects and continuously reaffirming knowledge from workshops.<br/><br/>
                Practicing agile software development through driver-navigator style collaborative pairing, daily stand-ups and retros which also working on group projects.<br/><br/>
                Final project at Makers, my group was very keen on working in a machine learning / AI project. We set ourselves a challenge to learn python, using libraries like OpenCV and utilising a pre-taught Neural network for face recognition. It was challenging project where we had to work together to research and apply new technologies, from which we achieved a working application that uses computer vision to control a Pong game build with Pygame, which was a lot of fun to build.
 - title: Content Prep Co-ordinator
   start: 2017
   end: 2019
   employer: The Walt Disney Company
   description: Responsible for researching, ordering and delivering both video and audio files to go onto the Disney+ app. The content I worked on was used for international launches and the continued development of the on demand app.<br/><br/>
                Worked with complex spreadsheet trackers to coordinate workflow of individual files and inputting detailed content.<br/><br/>
                Regularly co-ordinated with the team based at multiple locations to meet launch deadlines.
 - title: Self-employed Massage Therapist
   start: 2015
   end: 2017
   employer: Peace and Relax Massage Therapy
   description: Worked on a self-employed basis as a massage therapist.
 - title: Digital Media Operator
   start: 2012
   end: 2015
   employer: Technicolor Creative Services
   description: Created work for many well-known clients such as Google, Disney, Sky and Warner Bros.<br/><br/>
                Successfully launched a mass migration project to digitise IMGs archive content on behalf of Technicolor at their facilities.<br/><br/>
                Upkeep of relevant spreadsheets to be routinely shared with Technicolor accounts team and with the IMG media asset management team.<br/><br/>
                Liaised with the client to have a timely and organised delivery of assets created by the Samma Robot.<br/><br/>
                Regularly communicated with staff and clients at all levels of the organisation.
 - title: Media Library Operator
   start: 2010
   end: 2012
   employer: Technicolor Creative Services
   description: Retrieved requested media from the vast library on site.  This media would then be distributed in-house, nationally and internationally, as per the client’s request.<br/><br/>
                Implementation of a more efficient cataloguing system, which improved working processes at the Technicolor physical library.
#Education is required
education:
 - level: Vocational Education
   date: 2019
   subject: Software Development
   school: Makers Academy
 - level: ITEC Level 3 and 4
   date: 2014
   subject: Sports Massage Therapy
   school: Middlesex School of Complementary Medicine
 - level: ESOL Intermediate and Advanced English
   date: 2008
   subject: Equivalent to English GCSE

#This section is optional (as is the image link below)
codecademy:
   profileurl: https://www.codecademy.com/profiles/Pazoia
   courses:
    - title: Learn Ruby 
      link: https://www.codecademy.com/learn/learn-ruby
      date: November 11, 2019
    - title: Computer Science
      link: https://www.codecademy.com/learn/paths/computer-science
      date: To be completed

#List of interesting Github repo/projects to include - optional
github:
  - Pazoia/Pazoia.github.io
  - Peter2-71828/PongNotPong
  - Pazoia/PAZUL
  - Peter2-71828/MakersBNB
  - Megscode/acebook_undefined

intro: |
   I am a motivated full stack junior developer ready for a challenge and keen to keep learning. <br/><br/>
   I recently completed the Makers coding bootcamp, yet I have 20 years’ experience in other industries where I have developed excellent attention to detail, organisation, and communication skills.<br/><br/>
   I am currently building a game to enable me to learn Python and React and further my JavaScript knowledge.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
