# Site settings
title: Paulo Azoia
name: Paulo Azoia

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
  - title: GitHub
    url: https://github.com/Pazoia
  - title: LinkedIn
    url: https://www.linkedin.com/in/paulo-azoia-5b9045a0/

#Any buzzword skills you want to include
techskills:
  - Python
  - React
  - JavaScript
  - Ruby
  - HTML
  - CSS
  - Django
  - Ansible
  - TeamCity
  - Docker
  - Jasmine
  - Rspec
  - Pytest
  - Sinatra
  - Postgresql
  - ESLint / Prettier

personalskills:
  - Organisation
  - Attention to detail
  - Customer Service
  - Fluent English & Portuguese

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
  - title: Associate Software Engineer
    start: 2022
    end: Present
    employer: Eigen Technologies
    description:
      Improve user experience both in the back-end and front-end by contributing to new and
      existing features.
      <br/><br/>
      Working with a small team on the natural language processing (NLP) function to research &
      test the upgrade of licenced software within the platform and it's dependencies. Improving the
      NLP documentation to improve understanding of the code base and efficiency in future work.
      <br/><br/>
      Using Docker to test reliability of updates & deploy new versions of the product.
      <br/><br/>
      Pair programming on tasks ensuring code quality, refactoring tests and code base where
      possible to increase the product performance and code readability.

  - title: Software Developer Student
    start: 2020
    end: 2020
    employer: Makers Academy Bootcamp
    description:
      The bootcamp covered multiple languages throughout including Ruby
      JavaScript and HTML which promoted the ability
      of being language agnostic and challenging me to apply these languages in practical projects.
      <br/><br/>
      Understand Test Driven Development and the long-term benefits of using it.
      <br/><br/>
      Confidently research using docs, google and stackoverflow etc.
      <br/><br/>
      Practicing agile software development through driver-navigator style collaborative pairing, daily stand-ups and retros which also working on group projects.
      <br/><br/>
      Final project at Makers, my group was very keen on working in a machine learning / AI project. We set ourselves a challenge to learn python, using libraries like OpenCV and utilising a pre-taught Neural network for face recognition. It was challenging project where we had to work together to research and apply new technologies, from which we achieved a working application that uses computer vision to control a Pong game build with Pygame, which was a lot of fun to build.
  - title: Content Prep Co-ordinator
    start: 2017
    end: 2019
    employer: The Walt Disney Company
    description:
      Responsible for researching, ordering and delivering both video and
      files to go onto the Disney+ app. The
      content I worked on was used for international launches and the continued development of the on-demand app.
      <br/><br/>
      Worked with complex spreadsheet trackers to coordinate workflow of individual files and inputting detailed content.
      <br/><br/>
      Regularly coordinated with internal and external teams to meet launch deadlines.
  - title: Self-employed Massage Therapist
    start: 2015
    end: 2017
    employer: Peace and Relax Massage Therapy
    description: Worked on a self-employed basis as a massage therapist.
      <br/><br/>
      Meeting the client’s expectations by listening to their concerns, communicating clearly the effects of each treatment and deciding the correct approach.
      <br/><br/>
      I qualified in massage therapy whilst working at Technicolor, and in 2015 when Technicolor announced they were closing the site
      where I was working, I was grateful to have the chance to start my own business as a massage therapist.
      I really enjoyed the overall experience of being a small business owner, and how much of my personality I could bring to it.
  - title: Digital Media Operator
    start: 2012
    end: 2015
    employer: Technicolor Creative Services
    description:
      Created work for many well-known clients such as Google, Disney, Sky and
      Warner Bros.
      <br/><br/>
      Successfully launched a mass migration project to digitise IMGs archive content on behalf of Technicolor at their facilities.
      <br/><br/>
      Upkeep of relevant spreadsheets to be routinely shared with Technicolor accounts team and with the IMG media asset management team.
      <br/><br/>
      Liaised with the client to have a timely and organised delivery of assets created by the Samma Robot.
      <br/><br/>
      Regularly communicated with staff and clients at all levels of the organisation.
  - title: Media Library Operator
    start: 2010
    end: 2012
    employer: Technicolor Creative Services
    description:
      Retrieved requested media from the vast library on site.  This media would
      then be distributed in-house, nationally and internationally, as per the
      client’s request.
      <br/><br/>
      Implementation of a more efficient cataloguing system, which improved
      working processes at the Technicolor physical library.
#Education is required
education:
  - level: Makers Academy Graduation
    date: 2020
    subject: Software Development
    school: Makers Academy
  - level: ITEC Level 4 Certificate
    date: 2015
    subject: Sports Massage Therapy
    school: Middlesex School of Complementary Medicine
  - level: ITEC Level 3 and 4
    date: 2014
    subject: Swedish Massage Therapy
    school: Middlesex School of Complementary Medicine
  - level: ESOL Intermediate and Advanced English
    date: 2008
    subject: Equivalent to English GCSE

#This section is optional (as is the image link below)
codecademy:
  profileurl: https://www.codecademy.com/profiles/Pazoia
  courses:
    - title: Learn Ruby
      link: https://www.codecademy.com/learn/learn-ruby
      date: November 11, 2019

wes-bos:
  courses:
    - title: JavaScript30
      link: https://javascript30.com/
      date: February, 2021
    - title: JavaScript for Beginners
      link: https://beginnerjavascript.com/
      date: May, 2021
    - title: React for Beginners
      link: https://reactforbeginners.com/
      date: Jun, 2021
    - title: Advanced React and GraphQL
      link: https://advancedreact.com/
      date: In Progress

#List of interesting Github repo/projects to include - optional
github:
  - Pazoia/Where-is-my-Paradise
  - Pazoia/python-document-scraping-tool
  - Pazoia/PAZUL
  - Pazoia/PongNotPong

#Stackoverflow flair is optional
stackoverflow:
  profileurl: https://stackoverflow.com/users/258813/rhinds
  flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro:
  I am a motivated full-stack developer ready for a challenge and keen to keep learning.
  Coming from a background in digital media I was inspired by the opportunities to improve processes and data flow.
  <br/><br/>
  I am also an ambitious person who wants to succeed and grow, I’m not afraid to put the effort in to push myself forward, however,
  success to me isn’t about climbing the ladder as quickly as possible,
  it’s about feeling like I’ve contributed to something bigger and expanded my knowledge along the way.
  <br/><br/>
  As a friendly individual I enjoy collaborating with colleagues,
  learning from them and contributing to the join success of the company.
  My keen attention to detail helps me troubleshoot errors effectively and improve code continuously.
